### PR TITLE
Derrick/frontend refactor

### PR DESCRIPTION
**Pull request by derrick-yyang**
# PR Details
The PR details is mainly for @jasssse or whoever else wants to work on the frontend. There are 2 main things in this PR:
1. Frontend-refactor
2. Boilerplate API Integration code (MVVM) +`create/trips` API call as an example

I'll merge it on @jasssse 's approval. 

## 1. Frontend-refactor
I re-organized some of the code structure from our frontend to make it more decoupled and cleaner. I didn't really touch the pages that weren't trip-voting related since they had relatively simple components and stuff, so I only re-organized the 3 pages related to trip-voting:

### `DestinationsList.kt`
I moved all the components to `DestinationListComponents.kt` and kept only the page-structuring related stuff in the original file

### `DestinationsVotingList.kt`
I renamed this file to `VotingPhase.kt` and similarly moved all the components into it's own `VotingPhaseComponents.kt`

### `VotingResults.kt`
Did the same thing, moving all the specific components to another file `VotingResultsComponents.kt`. I know there was a shared component `DestinationEntry()` that's used by the first and last page, i just kept it in the VotingResults file and the first page imported from that, it's w/e imo but let me know if you guys are ok with that

## 2. API Integration + createTrip API call example
I added a couple files and classes to incorporate MVVM into our code and handle API calls. 
- `models/ViewModels.kt` : Contains our ViewModel in MVVM. This will manage the entire state of our frontend, according to the data models
- `models/DataModels.kt` : Contains the Data Models as described in our google doc
- `service/ApiManager.kt` :  Contains the API manager classes for our API calls to our backend. Currently just has a `TripRepository` class that is used to call all API's trip related

Aside from the new classes, I also updated the `MainActivity.kt` to initialize the API service, API Manager, and incorporate the UserViewModel. From all of these classes, I enabled calling the `/trips/` API from our backend in the TripConfiguration page. 

---
In general, what's left to do is just adding to the `ApiManagers.kt` code to call all our backend API's, and properly add and incorporate the `UserViewModel` into all of our pages. Also the error handling and fixing bugs

### CODE REVIEW

**Comment by danjelhuang** [comment]
Looks good, you tested the existing functionality of adding a trip right?

**Comment by derrick-yyang** [comment]
@danjelhuang yea I did, it should work... LOL. Could you pull this branch and also check yourself to see if it creates something?

**Comment by danjelhuang** [comment]
yeah it works for me as well

**Review by danjelhuang — APPROVED** [review]

**Review by jasssse — APPROVED** [review]
lgtm, this was a lot of important work thanks bro

**Pull request merged**
